// <auto-generated />
using System;
using DigitalCursos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalCursos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220308015845_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DigitalCursos.Models.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlunoId"), 1L, 1);

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"), 1L, 1);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CursoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            CargaHoraria = 1,
                            CursoNome = "Curso 1",
                            Descricao = "Descrição do curso 1",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 2,
                            CargaHoraria = 2,
                            CursoNome = "Curso 2",
                            Descricao = "Descrição do curso 2",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 3,
                            CargaHoraria = 3,
                            CursoNome = "Curso 3",
                            Descricao = "Descrição do curso 3",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 4,
                            CargaHoraria = 4,
                            CursoNome = "Curso 4",
                            Descricao = "Descrição do curso 4",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 5,
                            CargaHoraria = 5,
                            CursoNome = "Curso 5",
                            Descricao = "Descrição do curso 5",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 6,
                            CargaHoraria = 6,
                            CursoNome = "Curso 6",
                            Descricao = "Descrição do curso 6",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 7,
                            CargaHoraria = 7,
                            CursoNome = "Curso 7",
                            Descricao = "Descrição do curso 7",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 8,
                            CargaHoraria = 8,
                            CursoNome = "Curso 8",
                            Descricao = "Descrição do curso 8",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 9,
                            CargaHoraria = 9,
                            CursoNome = "Curso 9",
                            Descricao = "Descrição do curso 9",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 10,
                            CargaHoraria = 10,
                            CursoNome = "Curso 10",
                            Descricao = "Descrição do curso 10",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 11,
                            CargaHoraria = 11,
                            CursoNome = "Curso 11",
                            Descricao = "Descrição do curso 11",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 12,
                            CargaHoraria = 12,
                            CursoNome = "Curso 12",
                            Descricao = "Descrição do curso 12",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 13,
                            CargaHoraria = 13,
                            CursoNome = "Curso 13",
                            Descricao = "Descrição do curso 13",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 14,
                            CargaHoraria = 14,
                            CursoNome = "Curso 14",
                            Descricao = "Descrição do curso 14",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 15,
                            CargaHoraria = 15,
                            CursoNome = "Curso 15",
                            Descricao = "Descrição do curso 15",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 16,
                            CargaHoraria = 16,
                            CursoNome = "Curso 16",
                            Descricao = "Descrição do curso 16",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 17,
                            CargaHoraria = 17,
                            CursoNome = "Curso 17",
                            Descricao = "Descrição do curso 17",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 18,
                            CargaHoraria = 18,
                            CursoNome = "Curso 18",
                            Descricao = "Descrição do curso 18",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 19,
                            CargaHoraria = 19,
                            CursoNome = "Curso 19",
                            Descricao = "Descrição do curso 19",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 20,
                            CargaHoraria = 20,
                            CursoNome = "Curso 20",
                            Descricao = "Descrição do curso 20",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 21,
                            CargaHoraria = 21,
                            CursoNome = "Curso 21",
                            Descricao = "Descrição do curso 21",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 22,
                            CargaHoraria = 22,
                            CursoNome = "Curso 22",
                            Descricao = "Descrição do curso 22",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 23,
                            CargaHoraria = 23,
                            CursoNome = "Curso 23",
                            Descricao = "Descrição do curso 23",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 24,
                            CargaHoraria = 24,
                            CursoNome = "Curso 24",
                            Descricao = "Descrição do curso 24",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 25,
                            CargaHoraria = 25,
                            CursoNome = "Curso 25",
                            Descricao = "Descrição do curso 25",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 26,
                            CargaHoraria = 26,
                            CursoNome = "Curso 26",
                            Descricao = "Descrição do curso 26",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 27,
                            CargaHoraria = 27,
                            CursoNome = "Curso 27",
                            Descricao = "Descrição do curso 27",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 28,
                            CargaHoraria = 28,
                            CursoNome = "Curso 28",
                            Descricao = "Descrição do curso 28",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 29,
                            CargaHoraria = 29,
                            CursoNome = "Curso 29",
                            Descricao = "Descrição do curso 29",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 30,
                            CargaHoraria = 30,
                            CursoNome = "Curso 30",
                            Descricao = "Descrição do curso 30",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 31,
                            CargaHoraria = 31,
                            CursoNome = "Curso 31",
                            Descricao = "Descrição do curso 31",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 32,
                            CargaHoraria = 32,
                            CursoNome = "Curso 32",
                            Descricao = "Descrição do curso 32",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 33,
                            CargaHoraria = 33,
                            CursoNome = "Curso 33",
                            Descricao = "Descrição do curso 33",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 34,
                            CargaHoraria = 34,
                            CursoNome = "Curso 34",
                            Descricao = "Descrição do curso 34",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 35,
                            CargaHoraria = 35,
                            CursoNome = "Curso 35",
                            Descricao = "Descrição do curso 35",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 36,
                            CargaHoraria = 36,
                            CursoNome = "Curso 36",
                            Descricao = "Descrição do curso 36",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 37,
                            CargaHoraria = 37,
                            CursoNome = "Curso 37",
                            Descricao = "Descrição do curso 37",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 38,
                            CargaHoraria = 38,
                            CursoNome = "Curso 38",
                            Descricao = "Descrição do curso 38",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 39,
                            CargaHoraria = 39,
                            CursoNome = "Curso 39",
                            Descricao = "Descrição do curso 39",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 40,
                            CargaHoraria = 40,
                            CursoNome = "Curso 40",
                            Descricao = "Descrição do curso 40",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 41,
                            CargaHoraria = 41,
                            CursoNome = "Curso 41",
                            Descricao = "Descrição do curso 41",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 42,
                            CargaHoraria = 42,
                            CursoNome = "Curso 42",
                            Descricao = "Descrição do curso 42",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 43,
                            CargaHoraria = 43,
                            CursoNome = "Curso 43",
                            Descricao = "Descrição do curso 43",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 44,
                            CargaHoraria = 44,
                            CursoNome = "Curso 44",
                            Descricao = "Descrição do curso 44",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 45,
                            CargaHoraria = 45,
                            CursoNome = "Curso 45",
                            Descricao = "Descrição do curso 45",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 46,
                            CargaHoraria = 46,
                            CursoNome = "Curso 46",
                            Descricao = "Descrição do curso 46",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 47,
                            CargaHoraria = 47,
                            CursoNome = "Curso 47",
                            Descricao = "Descrição do curso 47",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 48,
                            CargaHoraria = 48,
                            CursoNome = "Curso 48",
                            Descricao = "Descrição do curso 48",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 49,
                            CargaHoraria = 49,
                            CursoNome = "Curso 49",
                            Descricao = "Descrição do curso 49",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 50,
                            CargaHoraria = 50,
                            CursoNome = "Curso 50",
                            Descricao = "Descrição do curso 50",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 51,
                            CargaHoraria = 51,
                            CursoNome = "Curso 51",
                            Descricao = "Descrição do curso 51",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 52,
                            CargaHoraria = 52,
                            CursoNome = "Curso 52",
                            Descricao = "Descrição do curso 52",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 53,
                            CargaHoraria = 53,
                            CursoNome = "Curso 53",
                            Descricao = "Descrição do curso 53",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 54,
                            CargaHoraria = 54,
                            CursoNome = "Curso 54",
                            Descricao = "Descrição do curso 54",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 55,
                            CargaHoraria = 55,
                            CursoNome = "Curso 55",
                            Descricao = "Descrição do curso 55",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 56,
                            CargaHoraria = 56,
                            CursoNome = "Curso 56",
                            Descricao = "Descrição do curso 56",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 57,
                            CargaHoraria = 57,
                            CursoNome = "Curso 57",
                            Descricao = "Descrição do curso 57",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 58,
                            CargaHoraria = 58,
                            CursoNome = "Curso 58",
                            Descricao = "Descrição do curso 58",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 59,
                            CargaHoraria = 59,
                            CursoNome = "Curso 59",
                            Descricao = "Descrição do curso 59",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 60,
                            CargaHoraria = 60,
                            CursoNome = "Curso 60",
                            Descricao = "Descrição do curso 60",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 61,
                            CargaHoraria = 61,
                            CursoNome = "Curso 61",
                            Descricao = "Descrição do curso 61",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 62,
                            CargaHoraria = 62,
                            CursoNome = "Curso 62",
                            Descricao = "Descrição do curso 62",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 63,
                            CargaHoraria = 63,
                            CursoNome = "Curso 63",
                            Descricao = "Descrição do curso 63",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 64,
                            CargaHoraria = 64,
                            CursoNome = "Curso 64",
                            Descricao = "Descrição do curso 64",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 65,
                            CargaHoraria = 65,
                            CursoNome = "Curso 65",
                            Descricao = "Descrição do curso 65",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 66,
                            CargaHoraria = 66,
                            CursoNome = "Curso 66",
                            Descricao = "Descrição do curso 66",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 67,
                            CargaHoraria = 67,
                            CursoNome = "Curso 67",
                            Descricao = "Descrição do curso 67",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 68,
                            CargaHoraria = 68,
                            CursoNome = "Curso 68",
                            Descricao = "Descrição do curso 68",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 69,
                            CargaHoraria = 69,
                            CursoNome = "Curso 69",
                            Descricao = "Descrição do curso 69",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 70,
                            CargaHoraria = 70,
                            CursoNome = "Curso 70",
                            Descricao = "Descrição do curso 70",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 71,
                            CargaHoraria = 71,
                            CursoNome = "Curso 71",
                            Descricao = "Descrição do curso 71",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 72,
                            CargaHoraria = 72,
                            CursoNome = "Curso 72",
                            Descricao = "Descrição do curso 72",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 73,
                            CargaHoraria = 73,
                            CursoNome = "Curso 73",
                            Descricao = "Descrição do curso 73",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 74,
                            CargaHoraria = 74,
                            CursoNome = "Curso 74",
                            Descricao = "Descrição do curso 74",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 75,
                            CargaHoraria = 75,
                            CursoNome = "Curso 75",
                            Descricao = "Descrição do curso 75",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 76,
                            CargaHoraria = 76,
                            CursoNome = "Curso 76",
                            Descricao = "Descrição do curso 76",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 77,
                            CargaHoraria = 77,
                            CursoNome = "Curso 77",
                            Descricao = "Descrição do curso 77",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 78,
                            CargaHoraria = 78,
                            CursoNome = "Curso 78",
                            Descricao = "Descrição do curso 78",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 79,
                            CargaHoraria = 79,
                            CursoNome = "Curso 79",
                            Descricao = "Descrição do curso 79",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 80,
                            CargaHoraria = 80,
                            CursoNome = "Curso 80",
                            Descricao = "Descrição do curso 80",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 81,
                            CargaHoraria = 81,
                            CursoNome = "Curso 81",
                            Descricao = "Descrição do curso 81",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 82,
                            CargaHoraria = 82,
                            CursoNome = "Curso 82",
                            Descricao = "Descrição do curso 82",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 83,
                            CargaHoraria = 83,
                            CursoNome = "Curso 83",
                            Descricao = "Descrição do curso 83",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 84,
                            CargaHoraria = 84,
                            CursoNome = "Curso 84",
                            Descricao = "Descrição do curso 84",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 85,
                            CargaHoraria = 85,
                            CursoNome = "Curso 85",
                            Descricao = "Descrição do curso 85",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 86,
                            CargaHoraria = 86,
                            CursoNome = "Curso 86",
                            Descricao = "Descrição do curso 86",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 87,
                            CargaHoraria = 87,
                            CursoNome = "Curso 87",
                            Descricao = "Descrição do curso 87",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 88,
                            CargaHoraria = 88,
                            CursoNome = "Curso 88",
                            Descricao = "Descrição do curso 88",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 89,
                            CargaHoraria = 89,
                            CursoNome = "Curso 89",
                            Descricao = "Descrição do curso 89",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 90,
                            CargaHoraria = 90,
                            CursoNome = "Curso 90",
                            Descricao = "Descrição do curso 90",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 91,
                            CargaHoraria = 91,
                            CursoNome = "Curso 91",
                            Descricao = "Descrição do curso 91",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 92,
                            CargaHoraria = 92,
                            CursoNome = "Curso 92",
                            Descricao = "Descrição do curso 92",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 93,
                            CargaHoraria = 93,
                            CursoNome = "Curso 93",
                            Descricao = "Descrição do curso 93",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 94,
                            CargaHoraria = 94,
                            CursoNome = "Curso 94",
                            Descricao = "Descrição do curso 94",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 95,
                            CargaHoraria = 95,
                            CursoNome = "Curso 95",
                            Descricao = "Descrição do curso 95",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 96,
                            CargaHoraria = 96,
                            CursoNome = "Curso 96",
                            Descricao = "Descrição do curso 96",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 97,
                            CargaHoraria = 97,
                            CursoNome = "Curso 97",
                            Descricao = "Descrição do curso 97",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 98,
                            CargaHoraria = 98,
                            CursoNome = "Curso 98",
                            Descricao = "Descrição do curso 98",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 99,
                            CargaHoraria = 99,
                            CursoNome = "Curso 99",
                            Descricao = "Descrição do curso 99",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 100,
                            CargaHoraria = 100,
                            CursoNome = "Curso 100",
                            Descricao = "Descrição do curso 100",
                            Inicio = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        });
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Aluno", b =>
                {
                    b.HasOne("DigitalCursos.Models.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Curso", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
